### ISSUE TITLE
Add button in custom location not working(v 2.1.23).

### ISSUE THREAD

**Issue by rameshlohala** [ninsuo/symfony-collection#110]
Add button in custom location is not working in version 2.1.23. even your demo site is not working for this.

**Comment by ninsuo** [comment]
Thanks, indeed I broke it when I fixed the nested collection prefix problem.
I won't be able to fix it that quickly (tough time!), please use 2.1.22 for a while.
I'll be doing it as soon as I can.

**Comment by diegocavalletti** [comment]
After a lot of headaches we found out the problem. Just find your custom location add button and check its data-collection value, copy that and add it as class to your button together with -action and -add suffix. With this the problem is fixed. I don't understand why the "setRightPrefix" function (new in 2.1.24) doesn't fix the button classes on his own, the code looks right but somehow it wasn't working for me.

Example:

`<button class="btn btn-default [collectionprefix]-action [collectionprefix]-add" data-collection="mycollection">My add new collection item button</button>`

Should become:

`<button class="btn btn-default [mycollection]-action [mycollection]-add" data-collection="mycollection">My add new collection item button</button>`

This fix the issue until something in the code doesn't properly fix this on his own

**Comment by jblf** [comment]
With 2.1.30, the following example works (considering "photos" is the underlying entity field using the CollectionType). Tested with no nested collection and no prefix configuration.

`<button class="btn btn-default {{ form.photos.vars.id }}-collection-action {{ form.photos.vars.id }}-collection-add" data-collection="{{ form.photos.vars.id }}">My add new collection item button</button>`

**Comment by pdhuaman** [comment]
This solution hasn't work for me. Button is displayed but it wont add a new section. Bundle works fine though.

> After a lot of headaches we found out the problem. Just find your custom location add button and check its data-collection value, copy that and add it as class to your button together with -action and -add suffix. With this the problem is fixed. I don't understand why the "setRightPrefix" function (new in 2.1.24) doesn't fix the button classes on his own, the code looks right but somehow it wasn't working for me.
> 
> Example:
> 
> `<button class="btn btn-default [collectionprefix]-action [collectionprefix]-add" data-collection="mycollection">My add new collection item button</button>`
> 
> Should become:
> 
> `<button class="btn btn-default [mycollection]-action [mycollection]-add" data-collection="mycollection">My add new collection item button</button>`
> 
> This fix the issue until something in the code doesn't properly fix this on his own
